# Generated by Django 5.1.2 on 2024-11-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techtrends_fn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
